### ISSUE TITLE
duplicate location "/robots.txt" when ingress has multipath

### ISSUE THREAD

**Issue by drawing** [alibaba/tengine-ingress#53]
when ingress config multipath and open `tengine-reload`, Ingress-Controller will generate locations where there are multiple robots.txt in the configuration.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - host: echo.w1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-service
            port:
              number: 80
      - path: /abc
        pathType: Prefix
        backend:
          service:
            name: echo-service-2
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tengine-ingress-configuration
  namespace: default
data:
  tengine-reload: 'true'
  tengine-static-service-cfg: 'true'
```
